name: test

on:
  push:

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Debug
        run: |
          export
          echo $PATH |
            tr ':' '\n' |
            while read p; do
              echo $p
              find $p -type l -print0 |
                xargs -0 ls -halw
            done

      - name: Shim
        run: |
          SHIMS=.brew-shims
          shim() {
              mkdir -p "$SHIMS"
              ln -s "$2" "$SHIMS/$1"
              sudo rm -f "$1"
              ln -s "$SHIMS/$1" .
              echo "shim $1 $2 $(readlink $1)"
          }
          (
              cd /usr/local/bin
              for file in $(find . -mindepth 1 -maxdepth 1 -type l); do
                  destination=$(readlink "$file")
                  case "$destination" in
                      ../Cellar/*)
                      ;;
                      ../Homebrew/*)
                      ;;
                      /*)
                          shim "$file" "$destination"
                      ;;
                      *)
                          shim "$file" "../$destination"
                      ;;
                  esac
              done
          )

      - name: Brew
        run: |
          brew update
          brew upgrade

      - name: Debug
        run: |
          export
          echo $PATH |
            tr ':' '\n' |
            while read p; do
              echo $p
              find $p -type l -print0 |
                xargs -0 ls -halw
            done
